# Generated by Django 3.1.2 on 2020-11-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('sku', models.CharField(max_length=20)),
            ],
        ),
    ]
