# Generated by Django 3.1.2 on 2020-11-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('In', 'In'), ('Out', 'Out'), ('Sale', 'Sale')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(choices=[('Nooks', 'Nooks'), ('In-house', 'In-house')], max_length=20)),
                ('note', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
