# Generated by Django 3.1.2 on 2020-11-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20201116_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
