# Generated by Django 3.1.2 on 2020-11-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='momo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
