# Generated by Django 3.1.2 on 2020-11-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_test_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='momo',
            field=models.IntegerField(null=True),
        ),
    ]
