# Generated by Django 3.1.2 on 2020-12-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20201202_1742'),
        ('inventory', '0016_transaction_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
