# Generated by Django 3.1.2 on 2020-12-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_product_sku_oshawa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_oshawa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
