# Generated by Django 3.1.2 on 2020-10-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='hst',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='net',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
