# Generated by Django 3.1.2 on 2020-11-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NooksPayoutSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payout_date', models.DateField()),
            ],
        ),
    ]
