# Generated by Django 3.1.2 on 2020-11-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_nookspayoutschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payout_schedule',
            field=models.ForeignKey(
                default=21, on_delete=django.db.models.deletion.RESTRICT, to='sales.nookspayoutschedule'),
            preserve_default=False,
        ),
    ]
