# Generated by Django 3.1.2 on 2020-11-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20201114_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='nooks_payout_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sales.nookspayoutschedule'),
        ),
    ]
