# Generated by Django 3.1.2 on 2020-11-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20201114_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='nookspayoutschedule',
            name='is_picked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
