# Generated by Django 3.1.2 on 2020-11-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_nookspayoutschedule_is_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='nooks_product_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
