# Generated by Django 3.1.2 on 2020-11-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_sale_nooks_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
    ]
