# Generated by Django 3.1.2 on 2020-11-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sale_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sku',
        ),
    ]
