# Generated by Django 3.1.2 on 2020-12-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20201202_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price_per_unit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
